apiVersion: v1
kind: Namespace
metadata:
  name: nexus-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: nexus-system
  labels:
    app: nexus
spec:
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: nexus
          image: sonatype/nexus3
          volumeMounts:
            - name: data
              mountPath: /nexus-data
          resources:
            requests:
              cpu: 10m
      hostname: nexus
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: nexus-system
  labels:
    app: nexus
spec:
  type: ClusterIP
  ports:
    - name: http-query
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: nexus
---