apiVersion: v1
kind: Namespace
metadata:
  name: sonarqube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: sonarqube-system
  labels:
    app: sonarqube
spec:
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: sonarqube
          image: sonarqube:lts 
          volumeMounts:
            - name: data
              mountPath: /opt/sonarqube/conf/
          resources:
            requests:
              cpu: 10m
      hostname: sonarqube 
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: sonarqube-system
  labels:
    app: sonarqube
spec:
  type: ClusterIP
  ports:
    - name: http-query
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: sonarqube
---